config/routes.rb
Rails.application.routes.draw do
  resources :paidemployment_applications
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :adminusers do
    collection do
    get 'viewapplicants'
  end
  end
  resources :questions
  resources :questions
  resources :applicants
  resources :internship_applications
  resources :adminusers do
    collection do
     get 'sendemails'
     get 'viewapplicants'
    end
    end
  resources :jobs
  devise_for :users
  get 'pages/about'

  get 'pages/contact'
  root 'pages#index'
  match '/pages/applicant_home', :to => 'pages#home', :via => [:get]
  match '/pages/applicant_show_job', :to => 'pages#showjob', :via => [:get]
  match '/pages/applicant_apply_job', :to => 'pages#applyjob', :via => [:get]
  match '/pages/applicant_show_questions', :to => 'pages#showquestions', :via => [:get, :post]

  match '/pages/paidemployment', :to => 'pages#paidemployment', :via => [:get, :post]
  match '/pages/volunteer', :to => 'pages#volunteer', :via => [:get, :post]
  match '/pages/intern_application_review', :to => 'pages#internreview', :via => [:get, :post]
  match '/pages/internship_application_success', :to => 'pages#internapplicationsuccess', :via => [:get, :post]

  match '/pages/paid_application_success', :to => 'pages#paidapplicationsuccess', :via => [:get, :post]

end

app/models/job.rb
class Job < ActiveRecord::Base
   belongs_to :adminuser
   has_many :questions, dependent: :destroy
   has_many :applications, dependent: :destroy
   #has_many :applicants, :through => :applications 
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.where(:adminuser_id => current_user.id)
    #@jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @questions=Question.where(:job_id => params[:id])
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.adminuser_id = current_user.id
    respond_to do |format|
      if @job.save
          format.html { redirect_to questions_path, notice: 'Job was successfully created.' }
          format.json { render :show, status: :created, location: @job }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def displayapplicantforjob
      @job = Job.find_by_id(params[:job_id])
      @internship_application = InternshipApplication.where(params[:job_id])
      @applicants = Applicant.where(:id => @internship_application.applicant_id)
      render template: "jobs/display_applicant_information"
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:id,:title, :description, :qualifications, :jobtype, :postedon, :deadline)
    end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-xs-6 col-xs-offset-3">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group col-xs-6 col-xs-offset-3">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group col-xs-6 col-xs-offset-3">
    <%= f.label :qualifications %><br>
    <%= f.text_area :qualifications, class: "form-control" %>
  </div>
  <div class="form-group col-xs-6 col-xs-offset-3">
    <%= f.label :postedon %><br>
    <%= f.date_select :postedon, class: "form-control" %>
  </div>
  <div class="form-group col-xs-6 col-xs-offset-3">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline, class: "form-control" %>
  </div>

  <div class="form-group col-xs-6 col-xs-offset-3">
    <%= f.label :jobtypelabel, "Job Type:" %>
    <br />
    <%= f.radio_button(:jobtype, "Internship") %>
    <%= f.label(:jobtype_internship, "internship") %>
    <br />
    <%= f.radio_button(:jobtype, "Paid Employment") %>
    <%= f.label(:jobtype_paidemployment, "paid employment") %>
    <br />
    <%= f.radio_button(:jobtype, "Volunteer") %>
    <%= f.label(:jobtype_volunteer, "volunteer") %>
    </div>

  <div class="actions col-xs-6 col-xs-offset-3">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/jobs/display_applicant_information.html.erb
<h1>Applicant Information</h1>
<% @applicants.each do |applicant| %>
  <p> First Name: <%= applicant.first_name %></p>
  <p> Last Name: <%= applicant.last_name %></p>
  <p> Email: <%= applicant.email %></p>
  <p> Contact: <%= applicant.contact %></p>
  <p> GPA: <%= applicant.gpa %></p>
  <p> Credit Hours: <%= applicant.credit_hours %></p>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job, class: "btn btn-link" %> |
<%= link_to 'Back', jobs_path, class: "btn btn-link" %>

app/views/jobs/index.html.erb
<head>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.4.0/fullcalendar.js"></script>
  <!--link rel='stylesheet' href='fullcalendar/fullcalendar.css' /-->
  <!--script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script-->

  <!--script src='lib/jquery.min.js'></script-->
  <!--script src='lib/momentjs.min.js'></script-->
  <!--script src='fullcalendar/fullcalendar.js'></script-->
</head>

<h1>Posted Jobs</h1>

<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Qualifications</th>
      <th>Postedon</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= job.qualifications %></td>
        <td><%= job.postedon %></td>
        <td><%= job.deadline %></td>
        <td><%= link_to 'Show', job, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_job_path(job), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <td><%= link_to 'Check Applicants', viewapplicants_adminusers_path(:job_id => job.id),  class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path, class: "btn btn-link" %>
<%= link_to 'Add Admin', new_adminuser_path, class: "btn btn-link" %>

<div id="calendar">
</div>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path, class: "btn btn-link" %>

app/views/jobs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Qualifications:</strong>
  <%= @job.qualifications %>
</p>

<p>
  <strong>Postedon:</strong>
  <%= @job.postedon %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @job.deadline %>
</p>
<p>
  <strong>Questions:</strong>
</p>

<% @questions.each do |question| %>
  <%= question.questions_list %>
  <br />
<% end %>
<br />
<%= link_to 'Edit', edit_job_path(@job), class: "btn btn-link" %> |
<%= link_to 'Back', jobs_path, class: "btn btn-link" %>

app/views/jobs/view_applicant_information.html.erb
<html>
<head>
<h1>Applicant Information</h1>
<% @applicants.each do |applicant| %>
  <p> First Name: <%= applicant.first_name %></p>
  <p> Last Name: <%= applicant.last_name %></p>
  <p> Email: <%= applicant.email %></p>
  <p> Contact: <%= applicant.contact %></p>
  <p> GPA: <%= applicant.gpa %></p>
  <p> Credit Hours: <%= applicant.credit_hours %></p>
<% end %>

<%= link_to "Go Back", jobs_path %>

<%= content_tag :div, class: "temp_information", data: { Mailtester: @Mailtester} do %>
<% end %>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/redmond/jquery-ui.css">

    <script type="text/javascript">
    $( document ).ready(function() {

      $("#poll").click(function() {
          $("#myDialog").dialog({height: 'auto', buttons: { "OK": function() { var answer; answer=$("#datepicker").val() ;$.ajax({type: 'GET', url: '/adminusers/sendemails',dataType: 'script',data: { subject: ("Interview scheduled for "+ answer) }  }); $(this).dialog("close"); } } });
      });
   });

    </script>

</head>
<body>
    <button id="poll">Click to Schedule Interview</button>
    <div id="myDialog" class="flora" title="Schedule Interview options" style="display: none;">
      <br>
      <p>Interview Scheduling Options for</p>
      <%= @user.firstname %></li><br/>
      <br>
      <label for="yes">Send Email Invitation :)</label><input type="radio" id="yes" value="yes25" name="question">
      <br/>
      <br>
      <label for="no">Send Rejection Mail   :( </label><input type="radio" id="no" value="no" name="question">
      <br/>
        <!-- add styles -->
      <link href="css/ui-lightness/jquery-ui-1.9.2.custom.min.css" rel="stylesheet" type="text/css" />

      <!-- add scripts -->
      <script src="js/jquery.191.js"></script>
      <script src="js/jquery-ui-1.9.2.custom.min.js"></script>

        <!--Interview Date(MM/DD/YY): <input type="text" id="first_name" />
        Interview Time: <input type="text" id="time_name" /> -->

        <!-- Adding calendar functionality-->
        Interview Date: <input id="datepicker" type="text" />

        <script>
           $(function(){
             $.datepicker.setDefaults(
               $.extend($.datepicker.regional[''])
             );
             $('#datepicker').datepicker();
           });
         </script>

    </div>

    <div style='color: green;' id='result'>
    </div>

</body>
</html>