config/routes.rb
Rails.application.routes.draw do
  resources :paidemployment_applications
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :adminusers do
    collection do
    get 'viewapplicants'
  end
  end
  resources :questions
  resources :questions
  resources :applicants
  resources :internship_applications
  resources :adminusers do
    collection do
     get 'sendemails'
     get 'viewapplicants'
    end
    end
  resources :jobs
  devise_for :users
  get 'pages/about'

  get 'pages/contact'
  root 'pages#index'
  match '/pages/applicant_home', :to => 'pages#home', :via => [:get]
  match '/pages/applicant_show_job', :to => 'pages#showjob', :via => [:get]
  match '/pages/applicant_apply_job', :to => 'pages#applyjob', :via => [:get]
  match '/pages/applicant_show_questions', :to => 'pages#showquestions', :via => [:get, :post]

  match '/pages/paidemployment', :to => 'pages#paidemployment', :via => [:get, :post]
  match '/pages/volunteer', :to => 'pages#volunteer', :via => [:get, :post]
  match '/pages/intern_application_review', :to => 'pages#internreview', :via => [:get, :post]
  match '/pages/internship_application_success', :to => 'pages#internapplicationsuccess', :via => [:get, :post]

  match '/pages/paid_application_success', :to => 'pages#paidapplicationsuccess', :via => [:get, :post]

end

app/models/adminuser.rb
class Adminuser < ActiveRecord::Base
   has_many :jobs, dependent: :destroy
   validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/controllers/adminusers_controller.rb
class AdminusersController < ApplicationController
  before_action :set_adminuser, only: [:show, :edit, :update, :destroy]
  # GET /adminusers
  # GET /adminusers.json
  def index
    @adminusers = Adminuser.all
  end

  # GET /adminusers/1
  # GET /adminusers/1.json
  def show
  end

  # GET /adminusers/new
  def new
    @adminuser = Adminuser.new
  end
    # <<<<<<< HEAD

  def sendemails
    @user=User.new( :firstname=> params[:subject] );
    @Mailtester=UserMailer.welcome_email(@user).deliver
    #redirect_to :action => 'viewapplicantinformation'
  end
# =======
#
 def viewapplicants
   @job = Job.find_by_id(params[:job_id])
   @applicants = Applicant.joins(:applications).where(applications: {status: "Submitted"})
                                               .where(applications: {job_id: params[:job_id]})
   render template: "adminusers/viewapplicants"
 end
# #=======
# def sendemails
#   @user=User.new( :firstname=> params[:subject] );
#   @Mailtester=UserMailer.welcome_email(@user).deliver
#   redirect_to :action => 'viewapplicantinformation'
# end
# #>>>>>>> e6b1b225c542ff112034bb5fade7eb2de6c16b30
# >>>>>>> 03ee3c0fb393983ef0f51c0e4250bd1162ab5907
  # GET /adminusers/1/edit
  def edit
  end

  # POST /adminusers
  # POST /adminusers.json
  def create
     @adminuser = Adminuser.new(adminuser_params)
     cost = 10
     pwd = ::BCrypt::Password.create(@adminuser.password, :cost => cost).to_s
     @user = User.new(:firstname => @adminuser.firstname, :updated_at => Time.now, :created_at => Time.now, :lastname => @adminuser.lastname, :contact => @adminuser.contact, :email => @adminuser.email, :encrypted_password => pwd, :admin => true)
     sign_in @user
  #   sign_in @user, :bypass => true
     respond_to do |format|
       if @adminuser.save
         format.html { redirect_to @adminuser, notice: 'Adminuser was successfully created.' }
         format.json { render :show, status: :created, location: @adminuser }
       else
         format.html { render :new }
         format.json { render json: @adminuser.errors, status: :unprocessable_entity }
       end
     end
   end
  # PATCH/PUT /adminusers/1
  # PATCH/PUT /adminusers/1.json
  def update
    respond_to do |format|
      if @adminuser.update(adminuser_params)
        format.html { redirect_to @adminuser, notice: 'Adminuser was successfully updated.' }
        format.json { render :show, status: :ok, location: @adminuser }
      else
        format.html { render :edit }
        format.json { render json: @adminuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adminusers/1
  # DELETE /adminusers/1.json
  def destroy
    @adminuser.destroy
    respond_to do |format|
      format.html { redirect_to adminusers_url, notice: 'Adminuser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adminuser
      @adminuser = Adminuser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adminuser_params
      params.require(:adminuser).permit(:firstname, :lastname, :email, :contact, :password, :passwordconfirmation)
    end
end

app/helpers/adminusers_helper.rb
module AdminusersHelper
end

app/views/adminusers/_form.html.erb
<%= form_for(@adminuser) do |f| %>
  <% if @adminuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adminuser.errors.count, "error") %> prohibited this adminuser from being saved:</h2>

      <ul>
      <% @adminuser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
   <%= f.label :firstname %><br>
   <%= f.text_field :firstname, class:"form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :lastname %><br>
   <%= f.text_field :lastname, class:"form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :contact %><br>
   <%= f.text_field :contact, class:"form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :email %><br>
   <%= f.text_field :email, class:"form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :password %><br>
   <% if @minimum_password_length %>
   <em>(<%= @minimum_password_length %> characters minimum)</em>
   <% end %>
   <%= f.password_field :password, class:"form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :passwordconfirmation %><br>
   <%= f.password_field :passwordconfirmation, class:"form-control" %>
 </div>
 <div class="form-group">
   <%= f.submit class:"btn btn-primary"%>
 </div>
<% end %>

app/views/adminusers/edit.html.erb
<h1>Editing Adminuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @adminuser %> |
<%= link_to 'Back', adminusers_path %>

app/views/adminusers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Adminusers</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Contact</th>
      <th>Password</th>
      <th>Passwordconfirmation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  </div>
    <div id="calendar">
  </div>

  <tbody>
    <% @adminusers.each do |adminuser| %>
      <tr>
        <td><%= adminuser.firstname %></td>
        <td><%= adminuser.lastname %></td>
        <td><%= adminuser.email %></td>
        <td><%= adminuser.contact %></td>
        <td><%= adminuser.password %></td>
        <td><%= adminuser.passwordconfirmation %></td>
        <td><%= link_to 'Show', adminuser %></td>
        <td><%= link_to 'Edit', edit_adminuser_path(adminuser) %></td>
        <td><%= link_to 'Destroy', adminuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adminuser', new_adminuser_path %>

app/views/adminusers/new.html.erb
<h1>New Adminuser</h1>

<%= render 'form' %>

<%= link_to 'Back', adminusers_path %>

app/views/adminusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @adminuser.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @adminuser.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @adminuser.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @adminuser.contact %>
</p>

<p>
  <strong>Password:</strong>
  <%= @adminuser.password %>
</p>

<p>
  <strong>Passwordconfirmation:</strong>
  <%= @adminuser.passwordconfirmation %>
</p>

<%= link_to 'Edit', edit_adminuser_path(@adminuser) %> |
<%= link_to 'Back', adminusers_path %>

app/views/adminusers/viewapplicantinformation.html.erb
<head>
<html xmlns="http://www.w3.org/1999/xhtml">

<h1>Applicant Information</h1>
<ol>
<li>Schedule Interview for </li>
<li><%= link_to @user.firstname,pages_contact_path  %></li>
<li>Schedule Interview for </li>
<li><%= @user2.firstname %></li>
</ol>
<%= link_to "Go Back", jobs_path %>

<%= content_tag :div, class: "temp_information", data: { Mailtester: @Mailtester} do %>
<% end %>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/redmond/jquery-ui.css">

    <script type="text/javascript">
    $( document ).ready(function() {

      $("#poll").click(function() {
          $("#myDialog").dialog({height: 'auto', buttons: { "OK": function() { var answer; answer=$("#datepicker").val() ;$.ajax({type: 'GET', url: '/adminusers/sendemails',dataType: 'script',data: { subject: ("Interview scheduled for "+ answer) }  }); $(this).dialog("close"); } } });
      });
   });

    </script>

</head>
<body>
    <button id="poll">Click to Schedule Interview</button>
    <div id="myDialog" class="flora" title="Schedule Interview options" style="display: none;">
      <br>
      <p>Interview Scheduling Options for</p>
      <%= @user.firstname %></li><br/>
      <br>
      <label for="yes">Send Email Invitation :)</label><input type="radio" id="yes" value="yes25" name="question">
      <br/>
      <br>
      <label for="no">Send Rejection Mail   :( </label><input type="radio" id="no" value="no" name="question">
      <br/>
        <!-- add styles -->
      <link href="css/ui-lightness/jquery-ui-1.9.2.custom.min.css" rel="stylesheet" type="text/css" />

      <!-- add scripts -->
      <script src="js/jquery.191.js"></script>
      <script src="js/jquery-ui-1.9.2.custom.min.js"></script>

        <!--Interview Date(MM/DD/YY): <input type="text" id="first_name" />
        Interview Time: <input type="text" id="time_name" /> -->

        <!-- Adding calendar functionality-->
        Interview Date: <input id="datepicker" type="text" />

        <script>
           $(function(){
             $.datepicker.setDefaults(
               $.extend($.datepicker.regional[''])
             );
             $('#datepicker').datepicker();
           });
         </script>

    </div>

    <div style='color: green;' id='result'>
    </div>

</body>
</html>

app/views/adminusers/viewapplicants.html.erb
<html>

<h1>Applicant Information</h1>

<% @applicants.each do |applicant| %>
  <p> First Name: <%= applicant.first_name %></p>
  <p> Last Name: <%= applicant.last_name %></p>
  <p> Email: <%= applicant.email %></p>
  <p> Contact: <%= applicant.contact %></p>
  <p> GPA: <%= applicant.gpa %></p>
  <p> Credit Hours: <%= applicant.credit_hours %></p>
<% end %>
<%= link_to "Go Back", jobs_path %>

</html>