config/routes.rb
Rails.application.routes.draw do
  resources :paidemployment_applications
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :adminusers do
    collection do
    get 'viewapplicants'
  end
  end
  resources :questions
  resources :questions
  resources :applicants
  resources :internship_applications
  resources :adminusers do
    collection do
     get 'sendemails'
     get 'viewapplicants'
    end
    end
  resources :jobs
  devise_for :users
  get 'pages/about'

  get 'pages/contact'
  root 'pages#index'
  match '/pages/applicant_home', :to => 'pages#home', :via => [:get]
  match '/pages/applicant_show_job', :to => 'pages#showjob', :via => [:get]
  match '/pages/applicant_apply_job', :to => 'pages#applyjob', :via => [:get]
  match '/pages/applicant_show_questions', :to => 'pages#showquestions', :via => [:get, :post]

  match '/pages/paidemployment', :to => 'pages#paidemployment', :via => [:get, :post]
  match '/pages/volunteer', :to => 'pages#volunteer', :via => [:get, :post]
  match '/pages/intern_application_review', :to => 'pages#internreview', :via => [:get, :post]
  match '/pages/internship_application_success', :to => 'pages#internapplicationsuccess', :via => [:get, :post]

  match '/pages/paid_application_success', :to => 'pages#paidapplicationsuccess', :via => [:get, :post]

end

app/views/pages/_internshipapplication.html.erb
<div class="field">
  <%= fa.label :first_name %><br>
  <%= fa.text_field :first_name %>
</div>
<div class="field">
  <%= fa.label :last_name %><br>
  <%= fa.text_field :last_name %>
</div>
<div class="field">
  <%= fa.label :email %><br>
  <%= fa.text_field :email %>
</div>
<div class="field">
  <%= fa.label :contact %><br>
  <%= fa.text_field :contact %>
</div>
<div class="field">
  <%= fa.label :gpa %><br>
  <%= fa.text_field :gpa %>
</div>
<div class="field">
  <%= fa.label :credit_hours %><br>
  <%= fa.number_field :credit_hours %>
</div>

app/views/pages/_paidemploymentapplication.html.erb
<div class="field">
  <%= fa.label :first_name %><br>
  <%= fa.text_field :first_name %>
</div>
<div class="field">
  <%= fa.label :last_name %><br>
  <%= fa.text_field :last_name %>
</div>
<div class="field">
  <%= fa.label :email %><br>
  <%= fa.text_field :email %>
</div>
<div class="field">
  <%= fa.label :contact %><br>
  <%= fa.text_field :contact %>
</div>
<div class="field">
  <%= fa.label :address %><br>
  <%= fa.text_field :address %>
</div>
<div class="field">
  <%= fa.label :city %><br>
  <%= fa.text_field :city %>
</div>
<div class="field">
  <%= fa.label :state %><br>
  <%= fa.text_field :state %>
</div>
<div class="field">
  <%= fa.label :zip %><br>
  <%= fa.text_field :zip %>
</div>
<div class="field">
  <%= fa.label :date_of_birth %><br>
  <%= fa.date_select :date_of_birth %>
</div>

app/views/pages/about.html.erb
<html>
<head>

  <link rel="stylesheet" type="text/css" href="jquery-background-video/jquery.background-video.css">
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="jquery-background-video/jquery.background-video.js"></script>
</head>
<body>

<h1>About Us</h1>

<p>At United Way of the Brazos Valley, we are committed to building a stronger community.
We believe in the power of community and that if we all work together, we make a greater impact than if we try to do it alone.
We help people learn, grow, aspire, and live their best lives. We work to achieve Bold Goals for our region in the areas of education,
financial stability and health that will advance the common good for all in our community.More than 5,000 donors, advocates, and volunteers are already part of our movement – and
we’re growing every day. You can join us. We have something for everyone – opportunities to support a cause close to your heart and improve our community for everyone. Get involved today!</p>
</body>
</html>

app/views/pages/applicant_apply_job.html.erb
<%= stylesheet_link_tag 'applicant_apply_job' %>
<div class="panel panel-default col-xs-6 col-xs-offset-3" id="profiledetails">
  <div class="panel-heading">
    <h3 class="panel-title">Profile details</h3>
  </div>
<%= form_for @applicant, :url => pages_applicant_show_questions_path(:job_id => @job.id) do |applicant| %>
  <%= applicant.fields_for :applicantdetails do |fa| %>
    <% if @job.jobtype == "Internship" %>
      <% render partial: "internshipapplication", :locals => {:fa => fa} %>
    <% elsif @job.jobtype == "Paid Employment" %>
      <% render partial: "paidemploymentapplication", :locals => {:fa => fa} %>
    <% else %>
      <% render partial: "volunteerapplication", :locals => {:fa => fa} %>
    <% end %>
  <% end %>
<div class="actions">
  <%= applicant.submit "Next", class:"btn btn-primary" %>
</div>
<% end %>
</div>

app/views/pages/applicant_home.html.erb
<%= stylesheet_link_tag 'applicant_home' %>
<div class="panel panel-default" id="jobsdiv">
  <div class="panel-heading">
    <h3 class="panel-title">Open jobs</h3>
  </div>
  <div class="table-responsive">
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Job type</th>
      <th>Deadline</th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
          <td><%= link_to job.title, pages_applicant_show_job_path(:job_id => job.id), class: "btn btn-link" %></td>
          <td><%= link_to job.jobtype, pages_applicant_show_job_path(:job_id => job.id), class: "btn btn-link" %></td>
          <td><%= link_to job.deadline, pages_applicant_show_job_path(:job_id => job.id), class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
</div>

app/views/pages/applicant_show_job.html.erb
<%= stylesheet_link_tag 'applicant_show_job' %>
<div class="panel panel-default col-xs-6 col-xs-offset-3" id="jobdetails">
  <div class="panel-heading">
    <h3 class="panel-title">Job details</h3>
  </div>
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Qualifications:</strong>
  <%= @job.qualifications %>
</p>

<p>
  <strong>Postedon:</strong>
  <%= @job.postedon %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @job.deadline %>
</p>

<%= link_to "Apply Now", pages_applicant_apply_job_path(:job_id => @job.id), class: "btn btn-primary col-xs-6 col-xs-offset-3" %>
</div>

app/views/pages/applicant_show_questions.html.erb
<%= form_for @internship_application, :url => pages_intern_application_review_path(:application_id => @application.id) do |internship_application| %>
    <div class="form-group col-xs-6 col-xs-offset-3">
    <p>Why would you like to intern for United Way of the Brazos Valley?</p>
    <%= internship_application.label :answer1 %><br>
    <%= internship_application.text_area :answer1, class: "form-control" %>
  </div>
  <div class="form-group col-xs-6 col-xs-offset-3">
    <p>How would your background enable you to succeed in that role at UWBV?</p>
    <%= internship_application.label :answer2 %><br>
    <%= internship_application.text_field :answer2, class: "form-control" %>
  </div>
  <div class="form-group col-xs-6 col-xs-offset-3">
    <p>Have you ever interned in United Way of the Brazos Valley or other United Way sites before?</p>
    <%= internship_application.label :answer3 %><br>
    <%= internship_application.text_field :answer3, class: "form-control" %>
  </div>
<div class="actions">
  <%= internship_application.submit class:"btn btn-primary" %>
</div>
<% end %>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p><b>Team Kryptonite</b><br>
Nikita Patil<br>
Sriya Nagesh<br>
Jacob Modayil<br>
Akshay<br>
Karthik<br>
Pooja Jhunjhunwala</p>

app/views/pages/index.html.erb
<div class="header">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-6 col-lg-offset-3 col-md-offset-3">
      <h1 class="wow fadeIn" data-wow-delay="0.2s"> Welcome to UWBV Careers</h1>
      <h3 class="wow fadeIn" data-wow-delay="0.8s">VOLUNTEER.                IMPACT.                CREATE.</h3>
      <ul class="list-inline wow fadeIn" data-wow-delay="1s">
        <li><%= link_to "Join Us", new_user_session_path, class:"btn btn-primary btn-lg" %></li>
      </div>
    </div>
  </div>
</div>
<!--END HEADER -->

<!--About-->

<div class="about" id="aboutus">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <h1>Our Values</h1>
        <br/><br/>
        <div class="row">
			<div class="col-lg-12 col-md-12">
				<ul class="list-inline">
					<li class="col-lg-3 col-md-3 col-sm-3 col-xs-6"><p class="wow fadeIn" data-wow-delay="1.5">Integrity</p></li>
					<li class="col-lg-3 col-md-3 col-sm-3 col-xs-6"><p class="wow fadeIn" data-wow-delay="1.7">Excellence</p></li>
					<li class="col-lg-3 col-md-3 col-sm-3 col-xs-6"><p class="wow fadeIn" data-wow-delay="1.9">Accountability</p></li>
					<li class="col-lg-3 col-md-3 col-sm-3 col-xs-6"><p class="wow fadeIn" data-wow-delay="2.1">Innovation</p></li>
				</ul>
      </div>
      </div>
      <br/><br/></br>
    <div class="row">
    <div class="col-lg-12 col-md-12 col-lg-offset-2 col-md-offset-2">
      <ul class="list-inline">
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-8"><p class="wow fadeIn" data-wow-delay="2.3">Leadership</p></li>
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-8"><p class="wow fadeIn" data-wow-delay="2.5">Selfless Service</p></li>
      </ul>
    </div>
    </div>
</br><br/>
    <h2 class="wow flipInX" data-wow-delay="0.3s">YOU can help build a stronger community!</h2>

    </div>
  </div>
</div>

<!-- Review -->

<div class="reviews" id="testimonials">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <h1 class="wow flipInX">Our Testimonials</h1>
        <h3>Here's what our employees have to say..</h3>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6 col-md-6 wow fadeInLeft" data-wow-delay="0.4s">
        <blockquote><img src="/img/kami.jpg" class="img-circle"/><p class="reviewspara">As a Human Resource Support Intern, I had a wonderful summer at United Way of the Brazos Valley working together with a group of brilliant people that strives to build a stronger community. I worked on three projects during the summer: Employee Benefits Study, New-Hire Orientation, and the development of an internship cohort program. I had the opportunity to learn about nonprofit management and operation by exposure to organizational documents, committee meetings, and conversation with managers from different departments. I appreciate the coaching and feedback from Alison on a lot of different subjects, and also thank for Brenda for training me on general HR duties.
          It was a valuable learning experience.</p><footer>Kami Xiong, <cite>Texas A&M University</cite></footer></blockquote>
      </div>
      <div class="col-lg-6 col-md-6 wow fadeInRight" data-wow-delay="0.8s">
        <blockquote><img src="/img/Selena.png" class="img-circle"/><p class="reviewspara">My internship experience with UWBV was phenomenal and provided me more work experience than my previous internships. As the Resource Development Intern, I was able to learn how to properly engage and recognize donors and other fundraising and campaign strategies. Not only did I learn a lot, but I enjoyed the UWBV team and their constant wisdom and encouragement. I always felt as though I could ask questions and that I was valued as an intern. To anyone deciding which internship experience to have before entering in to the professional world, I recommend working with United Way. While many may think it is "just" a nonprofit, I learned valuable business skills that I've been able to take with me in to my new career-
          and my internship solidified my passion for development!</p><footer>Selena Richey, <cite>Kids Matter International</cite></footer></blockquote>
      </div>
    </div>
  </div>
</div>
<!--End Reviews-->
<!-- CONTACT -->

	<div class="contact" id="contactus">
		<div class="container">

			<div class="row">
			<div class="col-lg-12 col-md-12">
				<h1>CONTACT US</h1>
				<p>Connect with us via:</p>

				<ul class="list-inline">
					<li><a href="https://www.facebook.com/unitedwaybv" target="blank"><i class="fa fa-facebook-official fa-4x wow fadeIn" data-wow-delay="0.4s" ></i></a></li>
					<li><a href="https://twitter.com/UWBV" target="blank"><i class="fa fa-twitter-square fa-4x wow fadeIn" data-wow-delay="0.6s"></i></a></li>
					<li><a href="https://vimeo.com/album/3549042" target="blank"><i class="fa fa-vimeo-square fa-4x wow fadeIn" data-wow-delay="0.8s"></i></a></li>
				</ul>

			</div>
			</div>

			<div class="row">
			<div class="col-lg-12 col-md-12">
				<p>Or connect with us via the information below</p>

				<ul class="list-inline">
					<li><i class="fa fa-map-marker"></i> 909 Southwest Pkwy E, College Station, TX 77840 </li>
					<li><i class="fa fa-phone"></i> (979)-696-4483</li>
					<li><i class="fa fa-envelope-o"></i> <a href="mailto:info@uwbv.org">info@uwbv.org</a></li>
				</ul>

			</div>
			</div>

		</div>
	</div>

	<!-- END CONTACT -->

<!--Footer-->

<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-4">
        <h3>UWBV</h3>
        <h4>Since 2015</h4>
        <h4><em>Creating measureable impact throughout the community.</em></h4>
      </div>

      <div class="col-lg-4 col-md-4">
        <h3>GET IN TOUCH!</h3>
        <h4><i class="fa fa-phone"></i> (979)-696-4483</h4>
        <h4><i class="fa fa-envelope-o"></i><a href="mailto:contact@uwbv.org">contact@uwbv.org</a></h4>
      </div>


      <div class="col-lg-4 col-md-4">
        <h3>ABOUT US</h3>
        <h4>Creating measureable impact throughout the community.</h4>
        <h4>UWBV &copy; 2015</h4>
        </div>
    </div>

<!--End footer-->

app/views/pages/internship.html.erb
<h1> Internship Questions Page </h1>

app/views/pages/internship_application_success.html.erb
<h1>Thank you for applying to our internship program at UWBV.</h1>
<h2> What's next?</h2>
<p> We will now carefully evaluate your application and get back to you at the earliest if
  your skills are a match to this position.
</p>

app/views/pages/paid_application_success.html.erb
<h1>Thank you for applying to our paid employment position at UWBV.</h1>
<h2> What's next?</h2>
<p> We will now carefully evaluate your application and get back to you at the earliest if
  your skills are a match to this position.
</p>

app/views/pages/paidemployment.html.erb
<h1> Paid Employment</h1>

app/views/pages/volunteer.html.erb
<h1>Volunteer</h1>