config/routes.rb
Rails.application.routes.draw do
  resources :paidemployment_applications
  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :adminusers do
    collection do
    get 'viewapplicants'
  end
  end
  resources :questions
  resources :questions
  resources :applicants
  resources :internship_applications
  resources :adminusers do
    collection do
     get 'sendemails'
     get 'viewapplicants'
    end
    end
  resources :jobs
  devise_for :users
  get 'pages/about'

  get 'pages/contact'
  root 'pages#index'
  match '/pages/applicant_home', :to => 'pages#home', :via => [:get]
  match '/pages/applicant_show_job', :to => 'pages#showjob', :via => [:get]
  match '/pages/applicant_apply_job', :to => 'pages#applyjob', :via => [:get]
  match '/pages/applicant_show_questions', :to => 'pages#showquestions', :via => [:get, :post]

  match '/pages/paidemployment', :to => 'pages#paidemployment', :via => [:get, :post]
  match '/pages/volunteer', :to => 'pages#volunteer', :via => [:get, :post]
  match '/pages/intern_application_review', :to => 'pages#internreview', :via => [:get, :post]
  match '/pages/internship_application_success', :to => 'pages#internapplicationsuccess', :via => [:get, :post]

  match '/pages/paid_application_success', :to => 'pages#paidapplicationsuccess', :via => [:get, :post]

end

app/models/paidemployment_application.rb
class PaidemploymentApplication < ActiveRecord::Base
end

app/controllers/paidemployment_applications_controller.rb
class PaidemploymentApplicationsController < ApplicationController
  before_action :set_paidemployment_application, only: [:show, :edit, :update, :destroy]

  # GET /paidemployment_applications
  # GET /paidemployment_applications.json
  def index
    @paidemployment_applications = PaidemploymentApplication.all
  end

  # GET /paidemployment_applications/1
  # GET /paidemployment_applications/1.json
  def show
  end

  # GET /paidemployment_applications/new
  def new
    @application = Application.find_by_id(params[:application_id])
    @paidemployment_application = PaidemploymentApplication.new
  end

  # GET /paidemployment_applications/1/edit
  def edit
  end

  # POST /paidemployment_applications
  # POST /paidemployment_applications.json
  def create
    @paidemployment_application = PaidemploymentApplication.new(paidemployment_application_params)

    respond_to do |format|
      if @paidemployment_application.save
        format.html { redirect_to @paidemployment_application, notice: 'Paidemployment application was successfully created.' }
        format.json { render :show, status: :created, location: @paidemployment_application }
      else
        format.html { render :new }
        format.json { render json: @paidemployment_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paidemployment_applications/1
  # PATCH/PUT /paidemployment_applications/1.json
  def update
    respond_to do |format|
      if @paidemployment_application.update(paidemployment_application_params)
        format.html { redirect_to @paidemployment_application, notice: 'Paidemployment application was successfully updated.' }
        format.json { render :show, status: :ok, location: @paidemployment_application }
      else
        format.html { render :edit }
        format.json { render json: @paidemployment_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paidemployment_applications/1
  # DELETE /paidemployment_applications/1.json
  def destroy
    @paidemployment_application.destroy
    respond_to do |format|
      format.html { redirect_to paidemployment_applications_url, notice: 'Paidemployment application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paidemployment_application
      @paidemployment_application = PaidemploymentApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paidemployment_application_params
      params.require(:paidemployment_application).permit(:applicant_id, :job_id, :application_id, :referral_source, :preferred_contact, :availability_date, :desired_salary, :transportation, :over_eighteen, :work_proof, :controlledsubstance_test, :a1, :a2, :a3, :a4, :a5, :a6, :a7, :a8)
    end
end

app/helpers/paidemployment_applications_helper.rb
module PaidemploymentApplicationsHelper
end

app/views/paidemployment_applications/_form.html.erb
<%= form_for(@paidemployment_application),:url => paidemployment_application_path(:application_id => flash[:application_id]) do |f| %>
  <% if @paidemployment_application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paidemployment_application.errors.count, "error") %> prohibited this paidemployment_application from being saved:</h2>

      <ul>
      <% @paidemployment_application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :applicant_id %><br>
    <%= f.number_field :applicant_id %>
  </div>
  <div class="field">
    <%= f.label :job_id %><br>
    <%= f.number_field :job_id %>
  </div>
  <div class="field">
    <%= f.label :application_id %><br>
    <%= f.number_field :application_id %>
  </div>
  <div class="field">
    <%= f.label :referral_source %><br>
    <%= f.text_area :referral_source %>
  </div>
  <div class="field">
    <%= f.label :preferred_contact %><br>
    <%= f.text_area :preferred_contact %>
  </div>
  <div class="field">
    <%= f.label :availability_date %><br>
    <%= f.date_select :availability_date %>
  </div>
  <div class="field">
    <%= f.label :desired_salary %><br>
    <%= f.number_field :desired_salary %>
  </div>
  <div class="field">
    <%= f.label :transportation %><br>
    <%= f.check_box :transportation %>
  </div>
  <div class="field">
    <%= f.label :over_eighteen %><br>
    <%= f.check_box :over_eighteen %>
  </div>
  <div class="field">
    <%= f.label :work_proof %><br>
    <%= f.check_box :work_proof %>
  </div>
  <div class="field">
    <%= f.label :controlledsubstance_test %><br>
    <%= f.check_box :controlledsubstance_test %>
  </div>
  <div class="field">
    <%= f.label :a1 %><br>
    <%= f.text_area :a1 %>
  </div>
  <div class="field">
    <%= f.label :a2 %><br>
    <%= f.text_area :a2 %>
  </div>
  <div class="field">
    <%= f.label :a3 %><br>
    <%= f.text_area :a3 %>
  </div>
  <div class="field">
    <%= f.label :a4 %><br>
    <%= f.text_area :a4 %>
  </div>
  <div class="field">
    <%= f.label :a5 %><br>
    <%= f.text_area :a5 %>
  </div>
  <div class="field">
    <%= f.label :a6 %><br>
    <%= f.text_area :a6 %>
  </div>
  <div class="field">
    <%= f.label :a7 %><br>
    <%= f.text_area :a7 %>
  </div>
  <div class="field">
    <%= f.label :a8 %><br>
    <%= f.text_area :a8 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paidemployment_applications/edit.html.erb
<h1>Editing Paidemployment Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @paidemployment_application %> |
<%= link_to 'Back', paidemployment_applications_path %>

app/views/paidemployment_applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Paidemployment Applications</h1>

<table>
  <thead>
    <tr>
      <th>Applicant</th>
      <th>Job</th>
      <th>Application</th>
      <th>Referral source</th>
      <th>Preferred contact</th>
      <th>Availability date</th>
      <th>Desired salary</th>
      <th>Transportation</th>
      <th>Over eighteen</th>
      <th>Work proof</th>
      <th>Controlledsubstance test</th>
      <th>A1</th>
      <th>A2</th>
      <th>A3</th>
      <th>A4</th>
      <th>A5</th>
      <th>A6</th>
      <th>A7</th>
      <th>A8</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paidemployment_applications.each do |paidemployment_application| %>
      <tr>
        <td><%= paidemployment_application.applicant_id %></td>
        <td><%= paidemployment_application.job_id %></td>
        <td><%= paidemployment_application.application_id %></td>
        <td><%= paidemployment_application.referral_source %></td>
        <td><%= paidemployment_application.preferred_contact %></td>
        <td><%= paidemployment_application.availability_date %></td>
        <td><%= paidemployment_application.desired_salary %></td>
        <td><%= paidemployment_application.transportation %></td>
        <td><%= paidemployment_application.over_eighteen %></td>
        <td><%= paidemployment_application.work_proof %></td>
        <td><%= paidemployment_application.controlledsubstance_test %></td>
        <td><%= paidemployment_application.a1 %></td>
        <td><%= paidemployment_application.a2 %></td>
        <td><%= paidemployment_application.a3 %></td>
        <td><%= paidemployment_application.a4 %></td>
        <td><%= paidemployment_application.a5 %></td>
        <td><%= paidemployment_application.a6 %></td>
        <td><%= paidemployment_application.a7 %></td>
        <td><%= paidemployment_application.a8 %></td>
        <td><%= link_to 'Show', paidemployment_application %></td>
        <td><%= link_to 'Edit', edit_paidemployment_application_path(paidemployment_application) %></td>
        <td><%= link_to 'Destroy', paidemployment_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paidemployment application', new_paidemployment_application_path %>

app/views/paidemployment_applications/new.html.erb
<h1>New Paidemployment Application</h1>

<%= render 'form' %>

<%= link_to 'Back', paidemployment_applications_path %>

app/views/paidemployment_applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Applicant:</strong>
  <%= @paidemployment_application.applicant_id %>
</p>

<p>
  <strong>Job:</strong>
  <%= @paidemployment_application.job_id %>
</p>

<p>
  <strong>Application:</strong>
  <%= @paidemployment_application.application_id %>
</p>

<p>
  <strong>Referral source:</strong>
  <%= @paidemployment_application.referral_source %>
</p>

<p>
  <strong>Preferred contact:</strong>
  <%= @paidemployment_application.preferred_contact %>
</p>

<p>
  <strong>Availability date:</strong>
  <%= @paidemployment_application.availability_date %>
</p>

<p>
  <strong>Desired salary:</strong>
  <%= @paidemployment_application.desired_salary %>
</p>

<p>
  <strong>Transportation:</strong>
  <%= @paidemployment_application.transportation %>
</p>

<p>
  <strong>Over eighteen:</strong>
  <%= @paidemployment_application.over_eighteen %>
</p>

<p>
  <strong>Work proof:</strong>
  <%= @paidemployment_application.work_proof %>
</p>

<p>
  <strong>Controlledsubstance test:</strong>
  <%= @paidemployment_application.controlledsubstance_test %>
</p>

<p>
  <strong>A1:</strong>
  <%= @paidemployment_application.a1 %>
</p>

<p>
  <strong>A2:</strong>
  <%= @paidemployment_application.a2 %>
</p>

<p>
  <strong>A3:</strong>
  <%= @paidemployment_application.a3 %>
</p>

<p>
  <strong>A4:</strong>
  <%= @paidemployment_application.a4 %>
</p>

<p>
  <strong>A5:</strong>
  <%= @paidemployment_application.a5 %>
</p>

<p>
  <strong>A6:</strong>
  <%= @paidemployment_application.a6 %>
</p>

<p>
  <strong>A7:</strong>
  <%= @paidemployment_application.a7 %>
</p>

<p>
  <strong>A8:</strong>
  <%= @paidemployment_application.a8 %>
</p>

<%= link_to 'Edit', edit_paidemployment_application_path(@paidemployment_application) %> |
<%= link_to 'Back', paidemployment_applications_path %>


<%= link_to 'Submit Application', pages_paid_application_success_path %>